# Site settings
theme: jekyll-theme-minimal
title: daxbi
description: Underhåller och utvecklar PBI-lösningar
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://daxbi.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# SEO settings
author: Your Name
bluesky:
  username: yourblueskyhandle
